FROM vinayakvispute/coder-server:latest

USER root
RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


USER coder

EXPOSE 8080

RUN mkdir -p /tmp/custom-workspace

CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "/tmp/custom-workspace"]
